server: 
  port: 9800
spring:
  profiles: dev #开发环境
  application:
    name: config_client
eureka:
  client:
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server: 
  port: 9801
spring:
  profiles: test #开发环境
  application:
    name: config_client
eureka:
  client:
    service-url: 
      defaultZone: http://eureka-test.com:7001/eureka/
